---
version: "2"
services:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_DOMAIN: "grafana.barrelmaker.dev"
      GF_SERVER_ROOT_URL: "https://grafana.barrelmaker.dev"
      GF_SERVER_ENFORCE_DOMAIN: "true"
      GF_SERVER_ENABLE_GZIP: "true"
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_SECURITY_COOKIE_SAMESITE: "strict"
      GF_SECURITY_X_CONTENT_TYPE_OPTIONS: "false"
      GF_EXTERNAL_IMAGE_STORAGE_PROVIDER: "local"
    volumes:
      - "/volume1/docker/grafana:/var/lib/grafana"
    restart: unless-stopped

  # loki:
  #   container_name: loki
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "/volume1/docker/prometheus/prometheus:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=90d"
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro"

  nut-exporter:
    container_name: nut-exporter
    image: ghcr.io/barrelmaker97/nut-exporter:latest
    environment:
      UPS_HOST: "pollux.lan"
    restart: unless-stopped

  kuma:
    container_name: kuma
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - "/volume1/docker/kuma:/app/data"
