---
version: "3.7"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_ROOT_URL: "https://grafana.barrelmaker.dev"
      GF_ENABLE_GZIP: "true"
    volumes:
      - type: bind
        source: /volume1/docker/grafana
        target: /var/lib/grafana
    restart: unless-stopped
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: /volume1/docker/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: bind
        source: /volume1/docker/prometheus/prometheus
        target: /prometheus
    restart: unless-stopped
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
    restart: unless-stopped
