---
version: "2"
services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
