---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nodes"
    static_configs:
      - targets:
          - "zeus.lan:9100"
        labels:
          node_name: "Zeus"
      - targets:
          - "pollux.lan:9100"
        labels:
          node_name: "Pollux"
      - targets:
          - "openwrt.lan:9100"
        labels:
          node_name: "Router"
      - targets:
          - "soteria.lan:9100"
        labels:
          node_name: "Soteria"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "nut"
    static_configs:
      - targets:
          - "nut-exporter:9120"

  - job_name: "grafana"
    static_configs:
      - targets:
          - "grafana:3000"

  - job_name: "unbound"
    static_configs:
      - targets:
          - "pollux.lan:9167"

  - job_name: "friendbot"
    static_configs:
      - targets:
          - "friendbot.barrelmaker.dev"

  - job_name: "minecraft"
    static_configs:
      - targets:
          - "niucraft2.barrelmaker.dev"
        labels:
          server_name: "NIUCraft2"
      - targets:
          - "motocraft.barrelmaker.dev"
        labels:
          server_name: "MotoCraft"
