---
version: "2"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      ADMIN_EMAIL: "nolancooper97@gmail.com"
      TZ: "America/Chicago"
      WEBUIBOXEDLAYOUT: "traditional"
      DNSMASQ_LISTENING: local
      DNSMASQ_USER: root
      WEBPASSWORD: ${WEBPASSWORD:?Must set WEBPASSWORD}
      DNS_FQDN_REQUIRED: "false"
      DNS_BOGUS_PRIV: "false"
      SKIPGRAVITYONBOOT: 1
      ServerIP: 192.168.15.30
      DNS1: "127.0.0.1#5335"
      DNS2: "127.0.0.1#5335"
    volumes:
      - "/home/barrelmaker/pihole/etc-pihole/:/etc/pihole/"
      - "/home/barrelmaker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
