---
version: "2"

services:
  watchtower:
    extends:
      file: ../watchtower/watchtower-compose.yaml
      service: watchtower
  node-exporter:
    extends:
      file: ../monitoring/node-exporter-compose.yaml
      service: node-exporter
  niucraft2:
    extends:
      file: ../minecraft/niucraft2-compose.yaml
      service: niucraft2
  motocraft:
    extends:
      file: ../minecraft/motocraft-compose.yaml
      service: motocraft
  motofactorio3:
    extends:
      file: ../factorio/moto3-compose.yaml
      service: motofactorio3
  friendbot:
    extends:
      file: ../friendbot/friendbot-compose.yaml
      service: friendbot
  redis:
    extends:
      file: ../friendbot/friendbot-compose.yaml
      service: redis
