---
version: "2"

services:
  watchtower:
    extends:
      file: ../watchtower/watchtower-compose.yaml
      service: watchtower
  grafana:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: grafana
  prometheus:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: prometheus
  alertmanager:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: alertmanager
  pistachio:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: pistachio
  node-exporter:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: node-exporter
  kuma:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: kuma
