---
version: "2"

services:
  watchtower:
    extends:
      file: ../watchtower/watchtower-compose.yaml
      service: watchtower
  grafana:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: grafana
  renderer:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: renderer
  prometheus:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: prometheus
  nut-exporter:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: nut-exporter
  node-exporter:
    extends:
      file: ../monitoring/monitoring-compose.yaml
      service: node-exporter
