---
version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      TZ: America/Chicago
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 3600
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
