---
version: "3.7"
services:
  friendbot:
    image: ghcr.io/barrelmaker97/friendbot:latest
    container_name: friendbot
    ports:
      - "6000:6000"
    environment:
      FRIENDBOT_EXPORT_ZIP: /export.zip
      FRIENDBOT_LOG_LEVEL: info
      FRIENDBOT_REDIS_HOST: redis
      FRIENDBOT_REDIS_PORT: 6379
      FRIENDBOT_SECRET_FILE: /friendbot-secret
      TZ: America/Chicago
    volumes:
      - type: bind
        source: /home/barrelmaker/export.zip
        target: /export.zip
        read_only: true
      - type: bind
        source: /home/barrelmaker/friendbot-secret
        target: /friendbot-secret
        read_only: true
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
