---
version: "3.7"
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    ports:
      - "8096:8096"
    volumes:
      - type: bind
        source: /volume1/docker/jellyfin/config
        target: /config
      - type: bind
        source: /volume1/docker/jellyfin/cache
        target: /cache
      - type: bind
        source: /volume1/local_only/content/media
        target: /media
    restart: "unless-stopped"
