---
version: "3.7"
services:
  motocraft:
    container_name: motocraft
    ports:
      - "25566:25565"
      - "8125:8123"
    environment:
      EULA: "TRUE"
      DIFFICULTY: normal
      OPS: Barrelmaker97
      MEMORY: 2G
      SERVER_NAME: MotoCraft
      MOTD: "MotoCraft Server"
      SPAWN_PROTECTION: 0
      FORCE_GAMEMODE: "true"
      VIEW_DISTANCE: 32
      TYPE: "BUKKIT"
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - type: bind
        source: /home/barrelmaker/gamedata/minecraft/motocraft-data
        target: /data
