---
version: "3.7"
services:
  niucraft1:
    container_name: niucraft1
    ports:
      - "25567:25565"
    environment:
      EULA: "TRUE"
      DIFFICULTY: normal
      OPS: Barrelmaker97
      MEMORY: 2G
      SERVER_NAME: NIUCraft1
      MOTD: "NIUCraft Server #1"
      SPAWN_PROTECTION: 0
      FORCE_GAMEMODE: "true"
      VIEW_DISTANCE: 32
      TYPE: "BUKKIT"
      TZ: America/Chicago
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - type: bind
        source: /home/barrelmaker/gamedata/minecraft/niucraft-data
        target: /data
