---
version: "3.7"
services:
  niuterraria:
    container_name: niuterraria
    image: kaysond/docker-terraria
    environment:
      PUID: "2415"
      PGID: "2415"
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - /home/barrelmaker/gamedata/terraria/niufriends-data/world:/world
      - /home/barrelmaker/gamedata/terraria/niufriends-data/config:/config
    restart: always
