version: "3.7"
services:
  server:
    container_name: localcraft
    ports:
      - "25570:25565"
      - "8124:8123"
    environment:
      EULA: "TRUE"
      DIFFICULTY: normal
      OPS: Barrelmaker97
      MEMORY: 2G
      SERVER_NAME: LocalCraft
      MOTD: "LocalCraft Server"
      SPAWN_PROTECTION: 0
      FORCE_GAMEMODE: "true"
      VIEW_DISTANCE: 32
      TYPE: "BUKKIT"
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - type: bind
        source: /home/barrelmaker/gamedata/minecraft/localcraft-data
        target: /data
