---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yamllint
        run: sudo apt install -y yamllint
      - name: Run yamllint
        run: yamllint .
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Compose Files
        run: find -name "*compose.yaml" -print0 | xargs -0 -n1 -I{} docker-compose -f {} config --services
        env:
          WEBPASSWORD: testpassword
